name: Publish to clojars

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Cache maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-

    - name: Set TAG value from refs/tags/TAG
      run: echo ::set-env name=GIT_TAG::${GITHUB_REF#refs/tags/}

    - name: Install java
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'

    - name: Overwrite pom.xml
      run: |
        sed -i 's;<version/>;<version>${{ env.GIT_TAG }}</version>;' pom.xml
        sed -i 's;<tag/>;<tag>${{ github.sha }}</tag>;' pom.xml

    - name: Deploy to Clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: mvn -s .m2/settings.xml deploy
